// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package scripts

import (
	"homework/internal/biz"
	"homework/internal/dao"
	"homework/internal/server"
	"homework/pkg/setting"
)

// Injectors from wire.go:

func Initial(addr string) (*server.Server, error) {
	settingSetting, err := setting.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := setting.NewDB(settingSetting)
	if err != nil {
		return nil, err
	}
	daoDao := dao.New(db)
	bizBiz := biz.New(daoDao)
	serverServer := server.New(addr, bizBiz)
	return serverServer, nil
}
